stages:
  - build-node
  - build-docker
  - publish-docker

variables:
  IMAGE_NAME: ${OCI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  IMAGE_NAME_LATEST: ${OCI_REGISTRY_IMAGE}:latest
  BUILD_NAME: "${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}@${CI_COMMIT_SHORT_SHA}"

build-node:
  stage: build-node
  image: node:lts-alpine
  retry:
    max: 1
    exit_codes:
      - 1
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
      variables:
        CI_ENVIRONMENT: "production"
    - when: never
  before_script:
    - cd ui
  script:
    - npx pnpm install --store-dir .pnpm --prefer-offline
    - npm run build
    - echo "${CI_COMMIT_SHA}" > dist/.app_commit_sha
  cache:
    key:
      files:
        - ui/package.json
      prefix: ${CI_PROJECT_NAMESPACE}@${CI_PROJECT_NAME}
    paths:
      - ui/.pnpm/
      - ui/node_modules/
  artifacts:
    name: "${BUILD_NAME}-ui"
    when: on_success
    paths:
      - ui/dist/
    expire_in: 2 weeks

.build-docker-base:
  stage: build-docker
  image: docker:cli
  services:
    - docker:dind
  dependencies:
    - build-node
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
      variables:
        CI_ENVIRONMENT: "production"
    - when: never
  before_script:
    - docker login --username "${OCI_REGISTRY_USER}" --password "${OCI_REGISTRY_PASSWORD}" "${OCI_REGISTRY}"
    - docker buildx create --name docker-container --driver docker-container --bootstrap --use
  script:
    - docker buildx build .
      --file docker/Dockerfile
      --platform "${IMAGE_PLATFORM}"
      --cache-from "type=registry,ref=${IMAGE_NAME_LATEST}"
      --cache-to "type=inline"
      --build-arg "APP_COMMIT_SHA=${CI_COMMIT_SHA}"
      --provenance false
      --output "type=image,oci-mediatypes=true,store=false,compression=zstd,compression-level=3,\"name=${OCI_REGISTRY_IMAGE}\",push=true,push-by-digest=true"
      --metadata-file "docker/buildx-metadata-${PLATFORM}.json"
  artifacts:
    name: "${BUILD_NAME}-build-docker-${PLATFORM}"
    when: on_success
    paths:
      - docker/
    expire_in: 1 weeks

build-docker-amd64:
  extends: .build-docker-base
  variables:
    PLATFORM: amd64
    IMAGE_PLATFORM: linux/amd64
  tags:
    - saas-linux-small-amd64

build-docker-arm64:
  extends: .build-docker-base
  variables:
    PLATFORM: arm64
    IMAGE_PLATFORM: linux/arm64/v8
  tags:
    - saas-linux-small-arm64

publish-docker:
  stage: publish-docker
  image: docker:cli
  services:
    - docker:dind
  dependencies:
    - build-docker-amd64
    - build-docker-arm64
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
      variables:
        CI_ENVIRONMENT: "production"
    - when: never
  variables:
    PLATFORM_AMD64: amd64
    PLATFORM_ARM64: arm64
  before_script:
    - apk add jq
    - docker login --username "${OCI_REGISTRY_USER}" --password "${OCI_REGISTRY_PASSWORD}" "${OCI_REGISTRY}"
  script:
    - IMAGE_DIGEST_AMD64=$(jq -r '."containerimage.digest"' < docker/buildx-metadata-${PLATFORM_AMD64}.json)
    - IMAGE_DIGEST_ARM64=$(jq -r '."containerimage.digest"' < docker/buildx-metadata-${PLATFORM_ARM64}.json)
    - docker manifest create "${IMAGE_NAME}" --amend "${OCI_REGISTRY_IMAGE}@${IMAGE_DIGEST_AMD64}" --amend "${OCI_REGISTRY_IMAGE}@${IMAGE_DIGEST_ARM64}"
    - docker manifest push "${IMAGE_NAME}"
    - docker manifest create "${IMAGE_NAME_LATEST}" --amend "${OCI_REGISTRY_IMAGE}@${IMAGE_DIGEST_AMD64}" --amend "${OCI_REGISTRY_IMAGE}@${IMAGE_DIGEST_ARM64}"
    - docker manifest push "${IMAGE_NAME_LATEST}"