# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration
# Used by publish-github-release in .gitlab-ci.yml

[changelog]
body = """
{% if version %}\
## {{ version }} — {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
## Unreleased
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}\
{% if commit.breaking %}[**breaking**] {% endif %}\
{{ commit.message | upper_first }}\
{% endfor %}
{% endfor %}
"""
trim = true
render_always = true

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
split_commits = false
protect_breaking_commits = false
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->Features" },
  { message = "^fix", group = "<!-- 1 -->Bug Fixes" },
  { message = "^doc", group = "<!-- 2 -->Documentation" },
  { message = "^perf", group = "<!-- 3 -->Performance" },
  { message = "^refactor", group = "<!-- 4 -->Refactor" },
  { message = "^style", group = "<!-- 5 -->Styling" },
  { message = "^test", group = "<!-- 6 -->Testing" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore\\(deps", skip = true },
  { message = "^chore|^ci", group = "<!-- 7 -->Miscellaneous" },
  { body = ".*security", group = "<!-- 8 -->Security" },
  { message = "^revert", group = "<!-- 9 -->Revert" },
  { message = ".*", group = "<!-- 10 -->Other" },
]
filter_commits = false
topo_order = false
sort_commits = "newest"
tag_pattern = "v[0-9]*"
ignore_tags = ".*pre.*|.*alpha.*|.*beta.*|.*rc.*"
