// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type WgPeer struct {
	ID                  int64
	PeerID              string
	Disabled            string
	Comment             *string
	PeerName            string
	PublicKey           string
	Interface           string
	AllowedAddress      string
	Endpoint            string
	EndpointPort        string
	PersistentKeepalive string
	SchedulerID         *string
	QueueID             *string
	ExpireTime          *string
	TrafficLimit        *string
	DownloadBandwidth   *string
	UploadBandwidth     *string
	DownloadUsage       *string
	UploadUsage         *string
}
