CREATE TABLE IF NOT EXISTS wg_peers (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    peer_id TEXT NOT NULL UNIQUE,
    disabled TEXT NOT NULL,
    comment TEXT,
    peer_name TEXT NOT NULL,
    public_key TEXT NOT NULL,
    interface TEXT NOT NULL,
    allowed_address TEXT NOT NULL,
    endpoint TEXT NOT NULL ,
    endpoint_port TEXT NOT NULL ,
    persistent_keepalive TEXT NOT NULL,
    scheduler_id TEXT,
    queue_id TEXT,
    expire_time TEXT,
    traffic_limit TEXT,
    download_bandwidth TEXT,
    upload_bandwidth TEXT,
    download_usage TEXT DEFAULT 0,
    upload_usage TEXT DEFAULT 0
);